---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talks-<ENV>
spec:
  selector:
    matchLabels:
      app: talks-<ENV>
  template:
    metadata:
      labels:
        app: talks-<ENV>
    spec:
      containers:
        - name: talks
          image: myhro/talks:<VERSION>
          ports:
            - containerPort: 3999
---
apiVersion: v1
kind: Service
metadata:
  name: talks-<ENV>
spec:
  selector:
    app: talks-<ENV>
  ports:
    - port: 3999
      targetPort: 3999
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: talks-<ENV>
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: <HOST>
      http:
        paths:
          - backend:
              serviceName: talks-<ENV>
              servicePort: 3999
  tls:
    - hosts:
        - <HOST>
      secretName: talks-<ENV>-tls
