---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talks-<ENV>
spec:
  selector:
    matchLabels:
      app: talks-<ENV>
  template:
    metadata:
      labels:
        app: talks-<ENV>
    spec:
      containers:
        - name: talks
          image: myhro/talks:<VERSION>
          ports:
            - containerPort: 3999
---
apiVersion: v1
kind: Service
metadata:
  name: talks-<ENV>
spec:
  selector:
    app: talks-<ENV>
  ports:
    - port: 3999
      targetPort: 3999
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: talks-<ENV>-tunnel
spec:
  selector:
    matchLabels:
      app: talks-<ENV>-tunnel
  serviceName: talks-<ENV>-tunnel
  template:
    metadata:
      labels:
        app: talks-<ENV>-tunnel
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2020.10.0
          command:
            - cloudflared
            - tunnel
            - run
            - <TUNNEL>
          env:
            - name: NO_AUTOUPDATE
              value: "true"
            - name: TUNNEL_URL
              value: http://talks-<ENV>:3999
          volumeMounts:
            - mountPath: /etc/cloudflared
              name: cloudflared
      volumes:
        - name: cloudflared
          secret:
            secretName: talks-<ENV>-tunnel
