---
name: Docker
"on": [push]
jobs:
  image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        run: |
          make build
          make push
  deploy-staging:
    needs: image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Credentials
        env:
          KUBECTL_CFG: ${{ secrets.KUBECTL_CFG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECTL_CFG" > $HOME/.kube/config
          kubectl version
      - name: Deploy
        run: |
          make deploy
  deploy-prod:
    if: github.ref == 'refs/heads/master'
    needs: image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Credentials
        env:
          KUBECTL_CFG: ${{ secrets.KUBECTL_CFG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECTL_CFG" > $HOME/.kube/config
          kubectl version
      - name: Deploy
        env:
          ENV: prod
          HOST: talks.myhro.info
        run: |
          make deploy
