---
name: Main
on:
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        env:
          GOBIN: /home/runner/go/bin
          GOPATH: /home/runner/go
        run: |
          make deps
          make build
      - name: Deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npm ci
          make deploy
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        env:
          GOBIN: /home/runner/go/bin
          GOPATH: /home/runner/go
        run: |
          make deps
          make build
      - name: Deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ENV: production
        run: |
          npm ci
          make deploy
