---
name: Main
on:
  - push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Build
        env:
          GOBIN: /home/runner/go/bin
          GOPATH: /home/runner/go
        run: |
          make deps
          make build
